apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wh307ebkb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wh307ebkb-go 
  name: wh307ebkb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wh307ebkb-go 
